version: '3.8'
services:
  webapp1:
    image: nginx
    restart: always
    ports:
      - "8000:80"

  webapp2:
    image: nginx
    restart: always
    ports:
      - "8003:80"

# 0.0.0.0:8000 port is map with container port :80